// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module student_infer_frame_streaming8_lane_worker8_4_Pipeline_READ_PIXEL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_in3_AWVALID,
        m_axi_gmem_in3_AWREADY,
        m_axi_gmem_in3_AWADDR,
        m_axi_gmem_in3_AWID,
        m_axi_gmem_in3_AWLEN,
        m_axi_gmem_in3_AWSIZE,
        m_axi_gmem_in3_AWBURST,
        m_axi_gmem_in3_AWLOCK,
        m_axi_gmem_in3_AWCACHE,
        m_axi_gmem_in3_AWPROT,
        m_axi_gmem_in3_AWQOS,
        m_axi_gmem_in3_AWREGION,
        m_axi_gmem_in3_AWUSER,
        m_axi_gmem_in3_WVALID,
        m_axi_gmem_in3_WREADY,
        m_axi_gmem_in3_WDATA,
        m_axi_gmem_in3_WSTRB,
        m_axi_gmem_in3_WLAST,
        m_axi_gmem_in3_WID,
        m_axi_gmem_in3_WUSER,
        m_axi_gmem_in3_ARVALID,
        m_axi_gmem_in3_ARREADY,
        m_axi_gmem_in3_ARADDR,
        m_axi_gmem_in3_ARID,
        m_axi_gmem_in3_ARLEN,
        m_axi_gmem_in3_ARSIZE,
        m_axi_gmem_in3_ARBURST,
        m_axi_gmem_in3_ARLOCK,
        m_axi_gmem_in3_ARCACHE,
        m_axi_gmem_in3_ARPROT,
        m_axi_gmem_in3_ARQOS,
        m_axi_gmem_in3_ARREGION,
        m_axi_gmem_in3_ARUSER,
        m_axi_gmem_in3_RVALID,
        m_axi_gmem_in3_RREADY,
        m_axi_gmem_in3_RDATA,
        m_axi_gmem_in3_RLAST,
        m_axi_gmem_in3_RID,
        m_axi_gmem_in3_RFIFONUM,
        m_axi_gmem_in3_RUSER,
        m_axi_gmem_in3_RRESP,
        m_axi_gmem_in3_BVALID,
        m_axi_gmem_in3_BREADY,
        m_axi_gmem_in3_BRESP,
        m_axi_gmem_in3_BID,
        m_axi_gmem_in3_BUSER,
        sext_ln13,
        tpsf_in_V_address0,
        tpsf_in_V_ce0,
        tpsf_in_V_we0,
        tpsf_in_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_in3_AWVALID;
input   m_axi_gmem_in3_AWREADY;
output  [63:0] m_axi_gmem_in3_AWADDR;
output  [0:0] m_axi_gmem_in3_AWID;
output  [31:0] m_axi_gmem_in3_AWLEN;
output  [2:0] m_axi_gmem_in3_AWSIZE;
output  [1:0] m_axi_gmem_in3_AWBURST;
output  [1:0] m_axi_gmem_in3_AWLOCK;
output  [3:0] m_axi_gmem_in3_AWCACHE;
output  [2:0] m_axi_gmem_in3_AWPROT;
output  [3:0] m_axi_gmem_in3_AWQOS;
output  [3:0] m_axi_gmem_in3_AWREGION;
output  [0:0] m_axi_gmem_in3_AWUSER;
output   m_axi_gmem_in3_WVALID;
input   m_axi_gmem_in3_WREADY;
output  [15:0] m_axi_gmem_in3_WDATA;
output  [1:0] m_axi_gmem_in3_WSTRB;
output   m_axi_gmem_in3_WLAST;
output  [0:0] m_axi_gmem_in3_WID;
output  [0:0] m_axi_gmem_in3_WUSER;
output   m_axi_gmem_in3_ARVALID;
input   m_axi_gmem_in3_ARREADY;
output  [63:0] m_axi_gmem_in3_ARADDR;
output  [0:0] m_axi_gmem_in3_ARID;
output  [31:0] m_axi_gmem_in3_ARLEN;
output  [2:0] m_axi_gmem_in3_ARSIZE;
output  [1:0] m_axi_gmem_in3_ARBURST;
output  [1:0] m_axi_gmem_in3_ARLOCK;
output  [3:0] m_axi_gmem_in3_ARCACHE;
output  [2:0] m_axi_gmem_in3_ARPROT;
output  [3:0] m_axi_gmem_in3_ARQOS;
output  [3:0] m_axi_gmem_in3_ARREGION;
output  [0:0] m_axi_gmem_in3_ARUSER;
input   m_axi_gmem_in3_RVALID;
output   m_axi_gmem_in3_RREADY;
input  [15:0] m_axi_gmem_in3_RDATA;
input   m_axi_gmem_in3_RLAST;
input  [0:0] m_axi_gmem_in3_RID;
input  [9:0] m_axi_gmem_in3_RFIFONUM;
input  [0:0] m_axi_gmem_in3_RUSER;
input  [1:0] m_axi_gmem_in3_RRESP;
input   m_axi_gmem_in3_BVALID;
output   m_axi_gmem_in3_BREADY;
input  [1:0] m_axi_gmem_in3_BRESP;
input  [0:0] m_axi_gmem_in3_BID;
input  [0:0] m_axi_gmem_in3_BUSER;
input  [62:0] sext_ln13;
output  [7:0] tpsf_in_V_address0;
output   tpsf_in_V_ce0;
output   tpsf_in_V_we0;
output  [15:0] tpsf_in_V_d0;

reg ap_idle;
reg m_axi_gmem_in3_RREADY;
reg tpsf_in_V_ce0;
reg tpsf_in_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln13_fu_94_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_in3_blk_n_R;
wire    ap_block_pp0_stage0;
reg   [7:0] t_9_reg_122;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] t_9_reg_122_pp0_iter1_reg;
reg   [15:0] gmem_in3_addr_read_reg_136;
wire   [63:0] zext_ln13_fu_111_p1;
reg   [7:0] t_fu_48;
wire   [7:0] add_ln13_fu_100_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_t_9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

student_infer_frame_streaming8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln13_fu_94_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_48 <= add_ln13_fu_100_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_48 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        gmem_in3_addr_read_reg_136 <= m_axi_gmem_in3_RDATA;
        t_9_reg_122 <= ap_sig_allocacmp_t_9;
        t_9_reg_122_pp0_iter1_reg <= t_9_reg_122;
    end
end

always @ (*) begin
    if (((icmp_ln13_fu_94_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_t_9 = 8'd0;
    end else begin
        ap_sig_allocacmp_t_9 = t_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_in3_blk_n_R = m_axi_gmem_in3_RVALID;
    end else begin
        gmem_in3_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_in3_RREADY = 1'b1;
    end else begin
        m_axi_gmem_in3_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tpsf_in_V_ce0 = 1'b1;
    end else begin
        tpsf_in_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tpsf_in_V_we0 = 1'b1;
    end else begin
        tpsf_in_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_100_p2 = (ap_sig_allocacmp_t_9 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_in3_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_in3_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (m_axi_gmem_in3_RVALID == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln13_fu_94_p2 = ((ap_sig_allocacmp_t_9 == 8'd135) ? 1'b1 : 1'b0);

assign m_axi_gmem_in3_ARADDR = 64'd0;

assign m_axi_gmem_in3_ARBURST = 2'd0;

assign m_axi_gmem_in3_ARCACHE = 4'd0;

assign m_axi_gmem_in3_ARID = 1'd0;

assign m_axi_gmem_in3_ARLEN = 32'd0;

assign m_axi_gmem_in3_ARLOCK = 2'd0;

assign m_axi_gmem_in3_ARPROT = 3'd0;

assign m_axi_gmem_in3_ARQOS = 4'd0;

assign m_axi_gmem_in3_ARREGION = 4'd0;

assign m_axi_gmem_in3_ARSIZE = 3'd0;

assign m_axi_gmem_in3_ARUSER = 1'd0;

assign m_axi_gmem_in3_ARVALID = 1'b0;

assign m_axi_gmem_in3_AWADDR = 64'd0;

assign m_axi_gmem_in3_AWBURST = 2'd0;

assign m_axi_gmem_in3_AWCACHE = 4'd0;

assign m_axi_gmem_in3_AWID = 1'd0;

assign m_axi_gmem_in3_AWLEN = 32'd0;

assign m_axi_gmem_in3_AWLOCK = 2'd0;

assign m_axi_gmem_in3_AWPROT = 3'd0;

assign m_axi_gmem_in3_AWQOS = 4'd0;

assign m_axi_gmem_in3_AWREGION = 4'd0;

assign m_axi_gmem_in3_AWSIZE = 3'd0;

assign m_axi_gmem_in3_AWUSER = 1'd0;

assign m_axi_gmem_in3_AWVALID = 1'b0;

assign m_axi_gmem_in3_BREADY = 1'b0;

assign m_axi_gmem_in3_WDATA = 16'd0;

assign m_axi_gmem_in3_WID = 1'd0;

assign m_axi_gmem_in3_WLAST = 1'b0;

assign m_axi_gmem_in3_WSTRB = 2'd0;

assign m_axi_gmem_in3_WUSER = 1'd0;

assign m_axi_gmem_in3_WVALID = 1'b0;

assign tpsf_in_V_address0 = zext_ln13_fu_111_p1;

assign tpsf_in_V_d0 = gmem_in3_addr_read_reg_136;

assign zext_ln13_fu_111_p1 = t_9_reg_122_pp0_iter1_reg;

endmodule //student_infer_frame_streaming8_lane_worker8_4_Pipeline_READ_PIXEL
