// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module student_infer_frame_streaming8_lane_worker8_6_Pipeline_WRITE_PIXEL_T_WRITE_PIXEL_O (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_out5_AWVALID,
        m_axi_gmem_out5_AWREADY,
        m_axi_gmem_out5_AWADDR,
        m_axi_gmem_out5_AWID,
        m_axi_gmem_out5_AWLEN,
        m_axi_gmem_out5_AWSIZE,
        m_axi_gmem_out5_AWBURST,
        m_axi_gmem_out5_AWLOCK,
        m_axi_gmem_out5_AWCACHE,
        m_axi_gmem_out5_AWPROT,
        m_axi_gmem_out5_AWQOS,
        m_axi_gmem_out5_AWREGION,
        m_axi_gmem_out5_AWUSER,
        m_axi_gmem_out5_WVALID,
        m_axi_gmem_out5_WREADY,
        m_axi_gmem_out5_WDATA,
        m_axi_gmem_out5_WSTRB,
        m_axi_gmem_out5_WLAST,
        m_axi_gmem_out5_WID,
        m_axi_gmem_out5_WUSER,
        m_axi_gmem_out5_ARVALID,
        m_axi_gmem_out5_ARREADY,
        m_axi_gmem_out5_ARADDR,
        m_axi_gmem_out5_ARID,
        m_axi_gmem_out5_ARLEN,
        m_axi_gmem_out5_ARSIZE,
        m_axi_gmem_out5_ARBURST,
        m_axi_gmem_out5_ARLOCK,
        m_axi_gmem_out5_ARCACHE,
        m_axi_gmem_out5_ARPROT,
        m_axi_gmem_out5_ARQOS,
        m_axi_gmem_out5_ARREGION,
        m_axi_gmem_out5_ARUSER,
        m_axi_gmem_out5_RVALID,
        m_axi_gmem_out5_RREADY,
        m_axi_gmem_out5_RDATA,
        m_axi_gmem_out5_RLAST,
        m_axi_gmem_out5_RID,
        m_axi_gmem_out5_RFIFONUM,
        m_axi_gmem_out5_RUSER,
        m_axi_gmem_out5_RRESP,
        m_axi_gmem_out5_BVALID,
        m_axi_gmem_out5_BREADY,
        m_axi_gmem_out5_BRESP,
        m_axi_gmem_out5_BID,
        m_axi_gmem_out5_BUSER,
        sext_ln21,
        sfd_out_V_address0,
        sfd_out_V_ce0,
        sfd_out_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_out5_AWVALID;
input   m_axi_gmem_out5_AWREADY;
output  [63:0] m_axi_gmem_out5_AWADDR;
output  [0:0] m_axi_gmem_out5_AWID;
output  [31:0] m_axi_gmem_out5_AWLEN;
output  [2:0] m_axi_gmem_out5_AWSIZE;
output  [1:0] m_axi_gmem_out5_AWBURST;
output  [1:0] m_axi_gmem_out5_AWLOCK;
output  [3:0] m_axi_gmem_out5_AWCACHE;
output  [2:0] m_axi_gmem_out5_AWPROT;
output  [3:0] m_axi_gmem_out5_AWQOS;
output  [3:0] m_axi_gmem_out5_AWREGION;
output  [0:0] m_axi_gmem_out5_AWUSER;
output   m_axi_gmem_out5_WVALID;
input   m_axi_gmem_out5_WREADY;
output  [15:0] m_axi_gmem_out5_WDATA;
output  [1:0] m_axi_gmem_out5_WSTRB;
output   m_axi_gmem_out5_WLAST;
output  [0:0] m_axi_gmem_out5_WID;
output  [0:0] m_axi_gmem_out5_WUSER;
output   m_axi_gmem_out5_ARVALID;
input   m_axi_gmem_out5_ARREADY;
output  [63:0] m_axi_gmem_out5_ARADDR;
output  [0:0] m_axi_gmem_out5_ARID;
output  [31:0] m_axi_gmem_out5_ARLEN;
output  [2:0] m_axi_gmem_out5_ARSIZE;
output  [1:0] m_axi_gmem_out5_ARBURST;
output  [1:0] m_axi_gmem_out5_ARLOCK;
output  [3:0] m_axi_gmem_out5_ARCACHE;
output  [2:0] m_axi_gmem_out5_ARPROT;
output  [3:0] m_axi_gmem_out5_ARQOS;
output  [3:0] m_axi_gmem_out5_ARREGION;
output  [0:0] m_axi_gmem_out5_ARUSER;
input   m_axi_gmem_out5_RVALID;
output   m_axi_gmem_out5_RREADY;
input  [15:0] m_axi_gmem_out5_RDATA;
input   m_axi_gmem_out5_RLAST;
input  [0:0] m_axi_gmem_out5_RID;
input  [9:0] m_axi_gmem_out5_RFIFONUM;
input  [0:0] m_axi_gmem_out5_RUSER;
input  [1:0] m_axi_gmem_out5_RRESP;
input   m_axi_gmem_out5_BVALID;
output   m_axi_gmem_out5_BREADY;
input  [1:0] m_axi_gmem_out5_BRESP;
input  [0:0] m_axi_gmem_out5_BID;
input  [0:0] m_axi_gmem_out5_BUSER;
input  [62:0] sext_ln21;
output  [8:0] sfd_out_V_address0;
output   sfd_out_V_ce0;
input  [15:0] sfd_out_V_q0;

reg ap_idle;
reg m_axi_gmem_out5_WVALID;
reg sfd_out_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln21_fu_123_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_out5_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln21_reg_254;
reg   [0:0] icmp_ln21_reg_254_pp0_iter1_reg;
reg   [0:0] icmp_ln21_reg_254_pp0_iter2_reg;
wire   [1:0] select_ln21_fu_153_p3;
reg   [1:0] select_ln21_reg_258;
wire   [7:0] select_ln21_3_fu_161_p3;
reg   [7:0] select_ln21_3_reg_263;
wire   [6:0] trunc_ln21_fu_169_p1;
reg   [6:0] trunc_ln21_reg_268;
wire   [8:0] add_ln24_fu_213_p2;
reg   [8:0] add_ln24_reg_273;
reg   [15:0] sfd_out_V_load_reg_288;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [63:0] zext_ln24_8_fu_219_p1;
wire    ap_block_pp0_stage0_01001;
reg   [1:0] o_3_fu_62;
wire   [1:0] add_ln22_fu_173_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_o_3_load;
reg   [7:0] t_fu_66;
reg   [7:0] ap_sig_allocacmp_t_load;
reg   [8:0] indvar_flatten_fu_70;
wire   [8:0] add_ln21_3_fu_129_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln22_fu_147_p2;
wire   [7:0] add_ln21_fu_141_p2;
wire   [8:0] tmp_s_fu_197_p3;
wire   [8:0] zext_ln24_fu_194_p1;
wire   [8:0] sub_ln24_fu_204_p2;
wire   [8:0] zext_ln24_7_fu_210_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

student_infer_frame_streaming8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln21_fu_123_p2 == 1'd0))) begin
            indvar_flatten_fu_70 <= add_ln21_3_fu_129_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_70 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln21_fu_123_p2 == 1'd0))) begin
            o_3_fu_62 <= add_ln22_fu_173_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            o_3_fu_62 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln21_fu_123_p2 == 1'd0))) begin
            t_fu_66 <= select_ln21_3_fu_161_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_66 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_reg_254 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln24_reg_273 <= add_ln24_fu_213_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln21_reg_254 <= icmp_ln21_fu_123_p2;
        icmp_ln21_reg_254_pp0_iter1_reg <= icmp_ln21_reg_254;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln21_reg_254_pp0_iter2_reg <= icmp_ln21_reg_254_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_fu_123_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln21_3_reg_263 <= select_ln21_3_fu_161_p3;
        select_ln21_reg_258 <= select_ln21_fu_153_p3;
        trunc_ln21_reg_268 <= trunc_ln21_fu_169_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_reg_254_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sfd_out_V_load_reg_288 <= sfd_out_V_q0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_fu_123_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln21_reg_254_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_70;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_o_3_load = 2'd0;
    end else begin
        ap_sig_allocacmp_o_3_load = o_3_fu_62;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 8'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_66;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_out5_blk_n_W = m_axi_gmem_out5_WREADY;
    end else begin
        gmem_out5_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_out5_WVALID = 1'b1;
    end else begin
        m_axi_gmem_out5_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sfd_out_V_ce0 = 1'b1;
    end else begin
        sfd_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_3_fu_129_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln21_fu_141_p2 = (ap_sig_allocacmp_t_load + 8'd1);

assign add_ln22_fu_173_p2 = (select_ln21_fu_153_p3 + 2'd1);

assign add_ln24_fu_213_p2 = (sub_ln24_fu_204_p2 + zext_ln24_7_fu_210_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_out5_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_out5_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln21_fu_123_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd405) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_147_p2 = ((ap_sig_allocacmp_o_3_load == 2'd3) ? 1'b1 : 1'b0);

assign m_axi_gmem_out5_ARADDR = 64'd0;

assign m_axi_gmem_out5_ARBURST = 2'd0;

assign m_axi_gmem_out5_ARCACHE = 4'd0;

assign m_axi_gmem_out5_ARID = 1'd0;

assign m_axi_gmem_out5_ARLEN = 32'd0;

assign m_axi_gmem_out5_ARLOCK = 2'd0;

assign m_axi_gmem_out5_ARPROT = 3'd0;

assign m_axi_gmem_out5_ARQOS = 4'd0;

assign m_axi_gmem_out5_ARREGION = 4'd0;

assign m_axi_gmem_out5_ARSIZE = 3'd0;

assign m_axi_gmem_out5_ARUSER = 1'd0;

assign m_axi_gmem_out5_ARVALID = 1'b0;

assign m_axi_gmem_out5_AWADDR = 64'd0;

assign m_axi_gmem_out5_AWBURST = 2'd0;

assign m_axi_gmem_out5_AWCACHE = 4'd0;

assign m_axi_gmem_out5_AWID = 1'd0;

assign m_axi_gmem_out5_AWLEN = 32'd0;

assign m_axi_gmem_out5_AWLOCK = 2'd0;

assign m_axi_gmem_out5_AWPROT = 3'd0;

assign m_axi_gmem_out5_AWQOS = 4'd0;

assign m_axi_gmem_out5_AWREGION = 4'd0;

assign m_axi_gmem_out5_AWSIZE = 3'd0;

assign m_axi_gmem_out5_AWUSER = 1'd0;

assign m_axi_gmem_out5_AWVALID = 1'b0;

assign m_axi_gmem_out5_BREADY = 1'b0;

assign m_axi_gmem_out5_RREADY = 1'b0;

assign m_axi_gmem_out5_WDATA = sfd_out_V_load_reg_288;

assign m_axi_gmem_out5_WID = 1'd0;

assign m_axi_gmem_out5_WLAST = 1'b0;

assign m_axi_gmem_out5_WSTRB = 2'd3;

assign m_axi_gmem_out5_WUSER = 1'd0;

assign select_ln21_3_fu_161_p3 = ((icmp_ln22_fu_147_p2[0:0] == 1'b1) ? add_ln21_fu_141_p2 : ap_sig_allocacmp_t_load);

assign select_ln21_fu_153_p3 = ((icmp_ln22_fu_147_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_o_3_load);

assign sfd_out_V_address0 = zext_ln24_8_fu_219_p1;

assign sub_ln24_fu_204_p2 = (tmp_s_fu_197_p3 - zext_ln24_fu_194_p1);

assign tmp_s_fu_197_p3 = {{trunc_ln21_reg_268}, {2'd0}};

assign trunc_ln21_fu_169_p1 = select_ln21_3_fu_161_p3[6:0];

assign zext_ln24_7_fu_210_p1 = select_ln21_reg_258;

assign zext_ln24_8_fu_219_p1 = add_ln24_reg_273;

assign zext_ln24_fu_194_p1 = select_ln21_3_reg_263;

endmodule //student_infer_frame_streaming8_lane_worker8_6_Pipeline_WRITE_PIXEL_T_WRITE_PIXEL_O
