# ============================================================================
# run_hls.tcl -- Vitis HLS project creation + csim + synthesis driver
# for the Seq2SeqLite student single-pixel int8 kernel.
# ============================================================================

open_project -reset seq2seqlite_student_proj

set_top student_infer_pixel

add_files src/student_top.cpp -cflags "-I src"
add_files src/student_hls_types.h -cflags "-I src"
add_files src/student_weight_convert.h -cflags "-I src"
add_files src/student_weights_int8.h -cflags "-I src"

# ---- Testbench + reference data ---------------------------------------
# csim requires the 5 raw experimental pixel CSVs (exported from MATLAB)
# and the 5 expected-output CSVs (generated by
# generate_expected_out_from_model.py from student_final.weights.h5).
# Data files MUST be registered with "add_files -tb" -- that is how
# Vitis HLS copies them into the csim build directory. They are not
# committed to the repo, so csim only runs when they are present in the
# directory this script is launched from; csynth always runs either way.
set tb_data_files [list \
    raw_pixel_1.csv raw_pixel_2.csv raw_pixel_3.csv raw_pixel_4.csv raw_pixel_5.csv \
    expected_out_1.csv expected_out_2.csv expected_out_3.csv expected_out_4.csv expected_out_5.csv \
]

set tb_data_present 1
foreach f $tb_data_files {
    if {![file exists $f]} {
        set tb_data_present 0
        puts "WARNING: testbench data file '$f' not found -- csim will be skipped."
    }
}

add_files -tb src/student_tb.cpp -cflags "-I src"
if {$tb_data_present} {
    foreach f $tb_data_files {
        add_files -tb $f
    }
}

open_solution -reset "solution1"

# ---- FPGA part selection -----------------------------------------------
# Confirmed exact part for the paper's target platform:
#   Opal Kelly XEM7360-K410T  ->  AMD/Xilinx Kintex-7 XC7K410T
#   Package: FFG676   Speed grade: -1   Temp grade: Commercial (C)
set_part {xc7k410t-1ffg676c}

# ---- Clock -----------------------------------------------------------
# 100 MHz is the board's low-jitter oscillator frequency (confirmed from
# Opal Kelly XEM7360 spec: "100 MHz and 200 MHz low-jitter clock
# oscillators"). 10 ns period, 2 ns uncertainty margin is a conservative
# default for a first synthesis pass.
create_clock -period 10 -name default

if {$tb_data_present} {
    csim_design -clean
} else {
    puts "INFO: skipping csim_design (testbench reference CSVs not present)."
}

csynth_design

# Uncomment once csim + csynth are both clean and you're ready to generate
# the IP / bitstream-ready RTL export:
# export_design -rtl verilog -format ip_catalog

exit