-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity student_infer_frame_streaming8_lane_worker8_4_Pipeline_WRITE_PIXEL_T_WRITE_PIXEL_O is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_out3_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_out3_AWREADY : IN STD_LOGIC;
    m_axi_gmem_out3_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out3_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out3_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out3_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out3_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out3_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out3_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out3_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out3_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out3_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_WVALID : OUT STD_LOGIC;
    m_axi_gmem_out3_WREADY : IN STD_LOGIC;
    m_axi_gmem_out3_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_out3_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out3_WLAST : OUT STD_LOGIC;
    m_axi_gmem_out3_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_out3_ARREADY : IN STD_LOGIC;
    m_axi_gmem_out3_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out3_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out3_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out3_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out3_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out3_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out3_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out3_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out3_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out3_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_RVALID : IN STD_LOGIC;
    m_axi_gmem_out3_RREADY : OUT STD_LOGIC;
    m_axi_gmem_out3_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_out3_RLAST : IN STD_LOGIC;
    m_axi_gmem_out3_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem_out3_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out3_BVALID : IN STD_LOGIC;
    m_axi_gmem_out3_BREADY : OUT STD_LOGIC;
    m_axi_gmem_out3_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out3_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out3_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln21 : IN STD_LOGIC_VECTOR (62 downto 0);
    sfd_out_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    sfd_out_V_ce0 : OUT STD_LOGIC;
    sfd_out_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of student_infer_frame_streaming8_lane_worker8_4_Pipeline_WRITE_PIXEL_T_WRITE_PIXEL_O is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_195 : STD_LOGIC_VECTOR (8 downto 0) := "110010101";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln21_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_out3_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln21_reg_254 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_reg_254_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_reg_254_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_fu_153_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln21_reg_258 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln21_5_fu_161_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln21_5_reg_263 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln21_fu_169_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln21_reg_268 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln24_fu_213_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln24_reg_273 : STD_LOGIC_VECTOR (8 downto 0);
    signal sfd_out_V_load_reg_288 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal zext_ln24_12_fu_219_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal o_5_fu_62 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln22_fu_173_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_o_5_load : STD_LOGIC_VECTOR (1 downto 0);
    signal t_fu_66 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_t_load : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_fu_70 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln21_5_fu_129_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln22_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln21_fu_141_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_197_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln24_fu_194_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln24_fu_204_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln24_11_fu_210_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component student_infer_frame_streaming8_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component student_infer_frame_streaming8_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln21_fu_123_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_70 <= add_ln21_5_fu_129_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_70 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    o_5_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln21_fu_123_p2 = ap_const_lv1_0))) then 
                    o_5_fu_62 <= add_ln22_fu_173_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    o_5_fu_62 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    t_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln21_fu_123_p2 = ap_const_lv1_0))) then 
                    t_fu_66 <= select_ln21_5_fu_161_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_66 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln21_reg_254 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln24_reg_273 <= add_ln24_fu_213_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln21_reg_254 <= icmp_ln21_fu_123_p2;
                icmp_ln21_reg_254_pp0_iter1_reg <= icmp_ln21_reg_254;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln21_reg_254_pp0_iter2_reg <= icmp_ln21_reg_254_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln21_fu_123_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln21_5_reg_263 <= select_ln21_5_fu_161_p3;
                select_ln21_reg_258 <= select_ln21_fu_153_p3;
                trunc_ln21_reg_268 <= trunc_ln21_fu_169_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln21_reg_254_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                sfd_out_V_load_reg_288 <= sfd_out_V_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln21_5_fu_129_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv9_1));
    add_ln21_fu_141_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_load) + unsigned(ap_const_lv8_1));
    add_ln22_fu_173_p2 <= std_logic_vector(unsigned(select_ln21_fu_153_p3) + unsigned(ap_const_lv2_1));
    add_ln24_fu_213_p2 <= std_logic_vector(unsigned(sub_ln24_fu_204_p2) + unsigned(zext_ln24_11_fu_210_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem_out3_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_out3_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem_out3_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_out3_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln21_fu_123_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln21_fu_123_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln21_reg_254_pp0_iter2_reg)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln21_reg_254_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_70)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_70;
        end if; 
    end process;


    ap_sig_allocacmp_o_5_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, o_5_fu_62, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_o_5_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_o_5_load <= o_5_fu_62;
        end if; 
    end process;


    ap_sig_allocacmp_t_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, t_fu_66)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_t_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_t_load <= t_fu_66;
        end if; 
    end process;


    gmem_out3_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem_out3_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_out3_blk_n_W <= m_axi_gmem_out3_WREADY;
        else 
            gmem_out3_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln21_fu_123_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv9_195) else "0";
    icmp_ln22_fu_147_p2 <= "1" when (ap_sig_allocacmp_o_5_load = ap_const_lv2_3) else "0";
    m_axi_gmem_out3_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_out3_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_out3_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_out3_ARID <= ap_const_lv1_0;
    m_axi_gmem_out3_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_out3_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_out3_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_out3_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_out3_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_out3_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_out3_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_out3_ARVALID <= ap_const_logic_0;
    m_axi_gmem_out3_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_out3_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_out3_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_out3_AWID <= ap_const_lv1_0;
    m_axi_gmem_out3_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_out3_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_out3_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_out3_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_out3_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_out3_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_out3_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_out3_AWVALID <= ap_const_logic_0;
    m_axi_gmem_out3_BREADY <= ap_const_logic_0;
    m_axi_gmem_out3_RREADY <= ap_const_logic_0;
    m_axi_gmem_out3_WDATA <= sfd_out_V_load_reg_288;
    m_axi_gmem_out3_WID <= ap_const_lv1_0;
    m_axi_gmem_out3_WLAST <= ap_const_logic_0;
    m_axi_gmem_out3_WSTRB <= ap_const_lv2_3;
    m_axi_gmem_out3_WUSER <= ap_const_lv1_0;

    m_axi_gmem_out3_WVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_out3_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_out3_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln21_5_fu_161_p3 <= 
        add_ln21_fu_141_p2 when (icmp_ln22_fu_147_p2(0) = '1') else 
        ap_sig_allocacmp_t_load;
    select_ln21_fu_153_p3 <= 
        ap_const_lv2_0 when (icmp_ln22_fu_147_p2(0) = '1') else 
        ap_sig_allocacmp_o_5_load;
    sfd_out_V_address0 <= zext_ln24_12_fu_219_p1(9 - 1 downto 0);

    sfd_out_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            sfd_out_V_ce0 <= ap_const_logic_1;
        else 
            sfd_out_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln24_fu_204_p2 <= std_logic_vector(unsigned(tmp_s_fu_197_p3) - unsigned(zext_ln24_fu_194_p1));
    tmp_s_fu_197_p3 <= (trunc_ln21_reg_268 & ap_const_lv2_0);
    trunc_ln21_fu_169_p1 <= select_ln21_5_fu_161_p3(7 - 1 downto 0);
    zext_ln24_11_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln21_reg_258),9));
    zext_ln24_12_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln24_reg_273),64));
    zext_ln24_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln21_5_reg_263),9));
end behav;
