#include "student_top.h"
#include <cstdio>
#include <cmath>
#include <fstream>
#include <sstream>
#include <string>


// ============================================================================
// Baseline + normalization matching training-time load_and_preprocess_mat
// (eval_experimental.py, function load_and_preprocess_mat).
//
// Real reference pipeline:
//   1. baseline[r,c] = mean(tp4d[r,c,0:BASELINE_BINS])   -- per-pixel mean of
//      the first BASELINE_BINS time bins.
//   2. tp4d[r,c,:] -= baseline[r,c]
//   3. clip negatives to 0
//   4. per-pixel max normalization: tp4d[r,c,:] /= max(tp4d[r,c,:])
//      (if max == 0 the pixel is left at 0 everywhere -- "invalid" pixel)
//
// BASELINE_BINS must equal the --baseline-bins value used when
// eval_experimental.py generated the reference outputs -- confirmed 10.
// ============================================================================
static const int BASELINE_BINS = 10;


static void preprocess_pixel(const double raw[SEQ_LEN], input_t out[SEQ_LEN]) {
    int n_baseline = (BASELINE_BINS < SEQ_LEN) ? BASELINE_BINS : SEQ_LEN;
    double baseline = 0.0;
    for (int t = 0; t < n_baseline; t++) {
        baseline += raw[t];
    }
    baseline /= (double)n_baseline;


    double corrected[SEQ_LEN];
    double max_val = 0.0;
    for (int t = 0; t < SEQ_LEN; t++) {
        double v = raw[t] - baseline;
        if (v < 0.0) v = 0.0;
        corrected[t] = v;
        if (v > max_val) max_val = v;
    }


    for (int t = 0; t < SEQ_LEN; t++) {
        double n = (max_val > 0.0) ? (corrected[t] / max_val) : 0.0;
        out[t] = input_t(n);
    }
}


// ----------------------------------------------------------------------------
// Loads a single pixel's SEQ_LEN raw values from a one-row CSV file.
// ----------------------------------------------------------------------------
static bool load_raw_pixel_csv(const std::string& path, double raw[SEQ_LEN]) {
    std::ifstream f(path);
    if (!f.is_open()) {
        printf("ERROR: could not open %s\n", path.c_str());
        return false;
    }
    std::string line;
    if (!std::getline(f, line)) {
        printf("ERROR: %s is empty\n", path.c_str());
        return false;
    }
    std::stringstream ss(line);
    std::string cell;
    int t = 0;
    while (std::getline(ss, cell, ',') && t < SEQ_LEN) {
        raw[t] = std::stod(cell);
        t++;
    }
    if (t != SEQ_LEN) {
        printf("ERROR: %s has %d values, expected %d\n", path.c_str(), t, SEQ_LEN);
        return false;
    }
    return true;
}


// ----------------------------------------------------------------------------
// Loads a pixel's REAL QKERAS MODEL output (i.e. the actual tensorflow +
// qkeras model.predict() result for this pixel, generated by
// generate_expected_out_from_model.py and written to expected_out_{idx}.csv)
// from a SEQ_LEN-row, N_OUT-column CSV file, one row per timestep, matching
// sfd_out[t][o]. This is the correctness reference for the HLS kernel --
// it is NOT physical/experimental ground truth. The HLS kernel is being
// verified against the trained model it is implementing, not against the
// physical fluorescence lifetime measured by the instrument.
// ----------------------------------------------------------------------------
static bool load_expected_out_csv(const std::string& path, double expected[SEQ_LEN][N_OUT]) {
    std::ifstream f(path);
    if (!f.is_open()) {
        printf("ERROR: could not open %s\n", path.c_str());
        return false;
    }
    std::string line;
    int t = 0;
    while (std::getline(f, line) && t < SEQ_LEN) {
        std::stringstream ss(line);
        std::string cell;
        int o = 0;
        while (std::getline(ss, cell, ',') && o < N_OUT) {
            expected[t][o] = std::stod(cell);
            o++;
        }
        if (o != N_OUT) {
            printf("ERROR: %s row %d has %d columns, expected %d\n", path.c_str(), t, o, N_OUT);
            return false;
        }
        t++;
    }
    if (t != SEQ_LEN) {
        printf("ERROR: %s has %d rows, expected %d\n", path.c_str(), t, SEQ_LEN);
        return false;
    }
    return true;
}


// ----------------------------------------------------------------------------
// Runs preprocess_pixel + student_infer_pixel on one pixel, compares against
// the real model's own output (expected_out_{idx}.csv), and extracts/reports
// lifetimes. A PASS here means the HLS kernel numerically reproduces the
// trained QKeras model, which is the actual correctness requirement for
// deploying this exact model onto the FPGA.
//
// Also reports the amplitude-weighted MEAN LIFETIME for BOTH the HLS output
// and the reference model output:
//     m = a1*tau1 + (1 - a1)*tau2,   with a1 = fret = amp1/(amp1+amp2)
// where tau1, tau2 and fret are produced by extract_lifetimes_pixel (the
// trapezoidal-integration definition in Appendix B of the manuscript). The
// mean-lifetime comparison is the quantity of physical interest: it states
// how far the FPGA kernel's reported lifetime lands from the reference
// model's, in nanoseconds, rather than in normalized decay units.
//
// Prints the first 20 timesteps side by side (HLS vs model, all 3 channels)
// and writes the FULL per-timestep comparison to hls_out_<tag>.csv
// (columns: t, hls0, hls1, hls2, exp0, exp1, exp2) in the csim run directory.
// ----------------------------------------------------------------------------
static double run_one_pixel_test(const std::string& tag,
                                  const double raw_pixel[SEQ_LEN],
                                  const double expected_out[SEQ_LEN][N_OUT],
                                  double &tau1_out,
                                  double &tau2_out,
                                  double &fret_out) {
    input_t  tpsf_in[SEQ_LEN];
    output_t sfd_out[SEQ_LEN][N_OUT];


    preprocess_pixel(raw_pixel, tpsf_in);
    student_infer_pixel(tpsf_in, sfd_out);


    double max_abs_err = 0.0;
    int max_t = -1, max_o = -1;
    for (int t = 0; t < SEQ_LEN; t++) {
        for (int o = 0; o < N_OUT; o++) {
            double got = (double)sfd_out[t][o];
            double err = std::fabs(got - expected_out[t][o]);
            if (err > max_abs_err) {
                max_abs_err = err;
                max_t = t;
                max_o = o;
            }
        }
    }


    printf("[%s] First 20 timesteps, HLS vs real QKeras model output:\n", tag.c_str());
    printf("[%s]   t |     hls0     exp0 |     hls1     exp1 |     hls2     exp2\n",
           tag.c_str());
    for (int t = 0; t < 20 && t < SEQ_LEN; t++) {
        printf("[%s] %3d | %8.5f %8.5f | %8.5f %8.5f | %8.5f %8.5f\n",
               tag.c_str(), t,
               (double)sfd_out[t][0], expected_out[t][0],
               (double)sfd_out[t][1], expected_out[t][1],
               (double)sfd_out[t][2], expected_out[t][2]);
    }


    std::string dump_path = "hls_out_" + tag + ".csv";
    std::ofstream dump(dump_path);
    if (dump.is_open()) {
        dump << "t,hls0,hls1,hls2,exp0,exp1,exp2\n";
        for (int t = 0; t < SEQ_LEN; t++) {
            dump << t << ","
                 << (double)sfd_out[t][0] << ","
                 << (double)sfd_out[t][1] << ","
                 << (double)sfd_out[t][2] << ","
                 << expected_out[t][0] << ","
                 << expected_out[t][1] << ","
                 << expected_out[t][2] << "\n";
        }
        dump.close();
        printf("[%s] Full 135-row comparison written to %s\n", tag.c_str(), dump_path.c_str());
    } else {
        printf("[%s] WARNING: could not open %s for writing\n", tag.c_str(), dump_path.c_str());
    }


    printf("[%s] Max abs error vs real QKeras model output: %f (t=%d, o=%d)\n",
           tag.c_str(), max_abs_err, max_t, max_o);
    printf("[%s] %s\n", tag.c_str(), (max_abs_err < 0.02) ? "PASS" : "FAIL");


    double tau1, tau2, fret;
    extract_lifetimes_pixel(sfd_out, tau1, tau2, fret);
    tau1_out = tau1;
    tau2_out = tau2;
    fret_out = fret;


    // Same extraction applied to the reference model output, so the two
    // lifetime sets are produced by identical arithmetic and differ only
    // through the decay sequences themselves.
    output_t expected_fixed[SEQ_LEN][N_OUT];
    for (int t = 0; t < SEQ_LEN; t++) {
        for (int o = 0; o < N_OUT; o++) {
            expected_fixed[t][o] = output_t(expected_out[t][o]);
        }
    }
    double tau1_gt, tau2_gt, fret_gt;
    extract_lifetimes_pixel(expected_fixed, tau1_gt, tau2_gt, fret_gt);


    // Amplitude-weighted mean lifetime: m = a1*tau1 + (1 - a1)*tau2,
    // with a1 = fret.
    double mean_hls = fret * tau1 + (1.0 - fret) * tau2;
    double mean_gt  = fret_gt * tau1_gt + (1.0 - fret_gt) * tau2_gt;


    printf("[%s] Lifetimes HLS: tau1=%f ns  tau2=%f ns  fret=%f\n",
           tag.c_str(), tau1, tau2, fret);
    printf("[%s] Lifetimes GT : tau1=%f ns  tau2=%f ns  fret=%f\n",
           tag.c_str(), tau1_gt, tau2_gt, fret_gt);
    printf("[%s] Mean lifetime  HLS=%f ns   GT=%f ns   abs_diff=%f ns\n",
           tag.c_str(), mean_hls, mean_gt, std::fabs(mean_hls - mean_gt));


    return max_abs_err;
}


int main() {
    // ------------------------------------------------------------------
    // 5 experimental pixels selected via ginput() in MATLAB from the same
    // af700 Accumulated.mat frame used to generate experimental_preds.mat.
    // raw_pixel_k.csv is the real experimental raw photon-count sequence
    // for pixel k, exported by the MATLAB extraction script using the
    // confirmed row-major pixel index mapping: preds_idx = (row-1)*ncols + col.
    //
    // expected_out_k.csv is NOT extracted from MATLAB / experimental data.
    // It is generated by generate_expected_out_from_model.py, which runs
    // raw_pixel_k.csv through the real TensorFlow + QKeras student model
    // (student_final.weights.h5 -- the exact weights this HLS kernel
    // implements) and writes model.predict() output directly. This file
    // is the correctness target for the HLS kernel, i.e. does the kernel
    // reproduce the model it is supposed to implement.
    // ------------------------------------------------------------------
    static const int NUM_PIXELS = 5;
    static const char* raw_paths[NUM_PIXELS] = {
        "raw_pixel_1.csv",
        "raw_pixel_2.csv",
        "raw_pixel_3.csv",
        "raw_pixel_4.csv",
        "raw_pixel_5.csv"
    };
    static const char* expected_paths[NUM_PIXELS] = {
        "expected_out_1.csv",
        "expected_out_2.csv",
        "expected_out_3.csv",
        "expected_out_4.csv",
        "expected_out_5.csv"
    };


    // Dataset-wide PHYSICAL reference statistics from experimental_stats.json
    // for student_final.weights.h5, computed over all 38335 valid pixels in
    // the full frame. This is a plausibility sanity check only -- it checks
    // that the lifetimes extracted from the HLS kernel's own output fall in
    // a physically reasonable range for this sample, NOT that they match
    // any per-pixel exact value. Failing this check does not mean the HLS
    // kernel is wrong; failing the max_abs_err PASS/FAIL check above does.
    static const double TAU1_REF_MIN = 0.1866115927696228;
    static const double TAU1_REF_MAX = 1.0598232746124268;
    static const double TAU2_REF_MIN = 0.2323022037744522;
    static const double TAU2_REF_MAX = 1.6713683605194092;
    static const double FRET_REF_MIN = 0.36633163690567017;
    static const double FRET_REF_MAX = 0.5031453371047974;


    double overall_max_err = 0.0;
    int n_failed = 0;
    int n_lifetime_out_of_range = 0;


    for (int k = 0; k < NUM_PIXELS; k++) {
        double raw_pixel[SEQ_LEN];
        double expected_out[SEQ_LEN][N_OUT];


        if (!load_raw_pixel_csv(raw_paths[k], raw_pixel)) {
            printf("FATAL: failed to load %s, aborting test\n", raw_paths[k]);
            return 1;
        }
        if (!load_expected_out_csv(expected_paths[k], expected_out)) {
            printf("FATAL: failed to load %s, aborting test\n", expected_paths[k]);
            return 1;
        }


        char tag[32];
        snprintf(tag, sizeof(tag), "pixel_%d", k + 1);


        double tau1, tau2, fret;
        double err = run_one_pixel_test(tag, raw_pixel, expected_out, tau1, tau2, fret);
        if (err > overall_max_err) overall_max_err = err;
        if (err >= 0.02) n_failed++;


        bool tau1_ok = (tau1 >= TAU1_REF_MIN && tau1 <= TAU1_REF_MAX);
        bool tau2_ok = (tau2 >= TAU2_REF_MIN && tau2 <= TAU2_REF_MAX);
        bool fret_ok = (fret >= FRET_REF_MIN && fret <= FRET_REF_MAX);
        if (!tau1_ok || !tau2_ok || !fret_ok) {
            n_lifetime_out_of_range++;
            printf("[%s] WARNING: lifetime(s) outside dataset-wide physical reference range "
                   "(tau1_ok=%d tau2_ok=%d fret_ok=%d)\n",
                   tag, tau1_ok, tau2_ok, fret_ok);
        }
    }


    printf("========================================\n");
    printf("Overall max abs error across %d pixels: %f\n", NUM_PIXELS, overall_max_err);
    printf("Pixels failed: %d / %d\n", n_failed, NUM_PIXELS);
    printf("Pixels with lifetime(s) outside dataset-wide physical reference range: %d / %d\n",
           n_lifetime_out_of_range, NUM_PIXELS);
    printf("Dataset-wide physical reference: tau1 in [%f, %f] ns, tau2 in [%f, %f] ns, "
           "fret in [%f, %f]\n",
           TAU1_REF_MIN, TAU1_REF_MAX, TAU2_REF_MIN, TAU2_REF_MAX,
           FRET_REF_MIN, FRET_REF_MAX);
    printf(n_failed == 0 ? "ALL PASS\n" : "SOME FAILED\n");


    return (n_failed == 0) ? 0 : 1;
}